//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaTable
    {
        public int Id { get; set; }
        public string HastalikTipi { get; set; }
        public string DiyetYontemi { get; set; }
        public int UserId { get; set; }
    
        public virtual UsersTable UsersTable { get; set; }
    }
}
